name: Cache GA Assignment

on: [push]

jobs:
  cache-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: prime-cache-6ca3d92
        id: cache-6ca3d92
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-6ca3d92-${{ runner.os }}
      
      - name: Show cache result
        run: echo "Cache hit: ${{ steps.cache-6ca3d92.outputs.cache-hit }}"
